name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build package
        run: pkgbuild --root . --identifier de.kuron-germany.michael.mainstage-devices --version ${{github.ref_name}} --install-location "Music/Audio Music Apps/MainStage Devices" --filter '.git*' --filter 'README.md' /tmp/mainstage-devices-pkg.pkg
      - name: Synthesize distribution
        run: productbuild --synthesize --package /tmp/mainstage-devices-pkg.pkg /tmp/distribution.xml
      - name: Edit distribution
        run: sed -i '' 's|</installer-gui-script>|<domains enable_anywhere="false" enable_currentUserHome="true" enable_localSystem="false"/></installer-gui-script>|g' /tmp/distribution.xml
      - name: Build product
        run: cd /tmp && productbuild --distribution /tmp/distribution.xml --version ${{github.ref_name}} --package-path /tmp/mainstage-devices-pkg.pkg /tmp/mainstage-devices.pkg && cd - && cp /tmp/mainstage-devices.pkg .
      - uses: actions/upload-artifact@v3
        with:
          name: mainstage-devices.pkg
          path: mainstage-devices.pkg
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: mainstage-devices.pkg
      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mainstage-devices.pkg
          asset_name: mainstage-devices.pkg
          tag: ${{ github.ref }}
          overwrite: true
